In [2]:
import torch

In [5]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
print(x.shape, x.numel())

torch.Size([12]) 12


In [7]:
print(x.reshape([3, 4]))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [9]:
print(torch.zeros([2, 4, 2]))
print(torch.ones([3, 2, 4]))

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [10]:
print(torch.tensor([1, 2]))

tensor([1, 2])


In [12]:
2 * x + 10

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [13]:
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [14]:
X = torch.arange(12, dtype=torch.float32).reshape([3, 4])
print(torch.cat([X, X], dim=0))
print(torch.cat([X, X], dim=1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.,  0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.,  8.,  9., 10., 11.]])


In [16]:
X.sum(axis=0)

tensor([12., 15., 18., 21.])

In [17]:
print(X[-1])

tensor([ 8.,  9., 10., 11.])


In [18]:
print(id(X))

4848269312


In [19]:
X.numpy()

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)