In [26]:
import torch

X = torch.arange(12).reshape([3, 4])
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
Y = X.clone()
Y[:] = 0
print(X, Y)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [7]:
X / X.sum(axis=1, keepdims=True)

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895]])

In [9]:
torch.dot(X[0], X[1])

tensor(38)

In [10]:
torch.mv(X, X[0])

tensor([14, 38, 62])

In [13]:
torch.mm(X, X.T)

tensor([[ 14,  38,  62],
        [ 38, 126, 214],
        [ 62, 214, 366]])

In [18]:
torch.norm(X + 0.0)

tensor(22.4944)

In [22]:
torch.mm(X, X[0].reshape([-1, 1]))

tensor([[14],
        [38],
        [62]])

In [27]:
torch.mm(X[:, 0].reshape([1, -1]), X)

tensor([[ 80,  92, 104, 116]])

In [31]:
torch.matmul(X[:, 0], X)

tensor([ 80,  92, 104, 116])