In [2]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True)
x.grad

In [4]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
print(x.grad)
y.backward()
print(x.grad)

None
tensor([ 0.,  4.,  8., 12.])


In [6]:
x.grad.zero_()
print(x, x.grad)

tensor([0., 1., 2., 3.], requires_grad=True) tensor([0., 0., 0., 0.])


In [10]:
y = x.sum()
y.backward()
x.grad

tensor([4., 4., 4., 4.])

In [12]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [13]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])

In [14]:
def f(a):
    return a + a * a / 10

x = torch.randn(size=[], requires_grad=True)
y = f(x)
y.backward()
x.grad

tensor(1.0624)